### ISSUE TITLE
Mbio: Accessing guest user analyses erring

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EbrcWebsiteCommon#125]
To replicate:
1. Pick any study on feature.mbio. You MUST be a guest!
2. Interact with the study so that the analysis gets saved (filter on a variable, add an app, etc). 
3. Do a hard refresh of the page (for me this is cmd shift R)
4. See large Error Could not load the analysis.

The above does not happen 1) on clinepi as a guest or 2) on feature.mbio while logged in.

**Comment by dmfalke** [comment]
Moving to EbrcWebsiteCommon for the time being

**Comment by dmfalke** [comment]
EDA services are sending a `Set-Cookie` header. I think for ClinEpiDB, these cookies are set to a subpath. This might need to be handled by @rbelnap.

**Comment by rbelnap** [comment]
The cookie setting (ProxyPassReverseCookiePath) wasn't set for feature.microbiomedb.org, because it was using a non-standard method for setting the proxy.  I've moved this over to the standard method, so it should now apply.  Let me know if that doesn't solve the issue.

**Comment by asizemore** [comment]
Wow that did it! Thanks @rbelnap !!
QA-ed on mbio.feature. Closing and moving to Complete
