### ISSUE TITLE
Site search feedback on links in hits (UI)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EbrcWebsiteCommon#128]
Discussed in 5/23/2022 EDA UX meeting

Currently the tables returned for variable and value hits have links on the study name and also the entity. We want to replace this with an additional column at the very left-hand side of the table that contains an icon for linking out directly to the variable in that row. Users can easily navigate to the study details tab from there if they’d like

For Study hits, we currently link to stand alone study pagesIn the site search result links we NEVER want to link to a stand alone study page. Instead, we should link to the study details tab in a new analysis

**Comment by nkittur-uga** [comment]
This works very nicely. In the case of pre-release studies, eg. searching for "Namibia", it gives you the "Namibia rfMDA RAVC Cluster Randomized Trial" hit and then redirects to the pre-release page. For all released studies, link-outs go to a new analysis page. QA is complete.
