### ISSUE TITLE
Study details tab: update summary information header

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EbrcWebsiteCommon#143]
Final mockups are here: https://www.figma.com/file/mDKIOrpnSwwMjz9acRg3qC/Add-data-accessibility-information-(study-details-%26-downloads-tabs)?node-id=47%3A365

<img width="849" alt="image" src="https://user-images.githubusercontent.com/25450900/172902071-0c2632ca-f171-41ce-8d67-0b3793591755.png">
 
**To do:** 
- [ ] Move data accessibility out of "data provenance" and into the summary header section
- [ ] Remove question mark "more information" icon next to "data accessibility"
- [ ] Add in text explaining data accessibility (see below)

_The ordering of attributes in the summary section has been moved to a new issue: #175_

**Text explaining data accessibility:**

**_For users who don’t have access permissions or are not logged in:_**

For studies with public access:
> Data downloads for this study are public. Data is available without logging in.

For studies with controlled access: 
> To download data please register or log in and `request access`.  Data will be available immediately following request submission. 

For studies with protected access:
> To download data please register or log in and `request access`.  Data will be available upon study team review and approval. 

**_For users who are logged in and have access to the study data:_**

For studies with public access:
> Data downloads for this study are public. Data is available without logging in.

For studies with controlled access: 
> You have been granted access to download the data. 

For studies with protected access:
> You have been granted access to download the data.

_Note: `request access` is a link that should take you to the popup:_

<img width="659" alt="image" src="https://user-images.githubusercontent.com/25450900/172904965-1c1a282a-6376-4b87-b31f-bb4e9e852ec1.png">

**Comment by dmfalke** [comment]
Most of this work can be done in https://github.com/VEuPathDB/EbrcWebsiteCommon/blob/master/Client/src/components/records/DatasetRecordClasses.DatasetRecordClass.jsx.

We will also want to remove the `record` scope from `study_access` in https://github.com/VEuPathDB/EbrcModelCommon/blob/3a629ddf723538410ba712db0f1771f465823f3c/Model/lib/wdk/ontology/commonIndividuals.txt#L63.

**Comment by sweverschulman** [comment]
<img width="1018" alt="Screen Shot 2022-11-04 at 11 10 23 AM" src="https://user-images.githubusercontent.com/62298921/200009398-0895b83d-e357-4f35-87a5-83f41abbbe57.png">

Changes seem to have not been made to the qa site. The ordering is still incorrect and there question mark.

**Comment by dmfalke** [comment]
It looks like I used the wrong scope for this attribute. I also missed the part about changing the order above. Note that the latter will impact genomic sites, so I think I will make a new issue for that and get feedback from the genomics ux group.

**Comment by SheenaTomko** [comment]
This is done
