### ISSUE TITLE
Site search results are displaying html code

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EbrcWebsiteCommon#149]
Instead of showing text in italics, the site search results display the html code:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/25450900/174871993-b60e3616-1f32-41be-b95d-39c396addcc7.png">

Please reformat to instead show italicized text. I think italics are the only issue, but please double check.

**Comment by nkittur-uga** [comment]
Looks good!
