### ISSUE TITLE
qa.restricted : enable register link for guest users

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EbrcWebsiteCommon#172]
The double login for the qa site is confusing for our providers, even when given a step-by-step guide. 

Decision:

**qa.restricted.clinepidb.org:** 
- We will replace the generic login to the restricted site with personal credentials on the 1st screen (this will log users into their VEuPathDB account as well as into the site). @rbelnap will need to be consulted about bypassing the generic login
- _Note: if no login is required to open the restricted site, providers accessing the study as a “Guest” may be confused as to why their study is missing_
- Providers will only be able to see the UNRELEASED studies (and unreleased study cards) to which they have been granted access (ie, their studies). Study cards for other pre-release studies will NOT be visible. Study cards for all released studies will be visible, with same access restrictions as the live site
- ClinEpi staff will be able too see ALL unreleased studies 

**qa.clinepidb.org:**
- Providers do NOT use this site
- We will keep the normal double-login (generic login information on the 1st screen, personal VEuPathDB login for ClinEpi staff to access all pre-release studies)

**Comment by SheenaTomko** [comment]
This looks great. Systems removed the gateway login, and now the user is automatically directed immediately to log into their ClinEpi account. Private studies are accessible only to those with study access

**Comment by dmfalke** [comment]
I'm reopening this because we need to allow guest users to access https://qa.restricted.clinepidb.org/ce.restricted.qa/app/user/forgot-password

**Comment by aurreco-uga** [comment]
this seems done

![Image](https://github.com/VEuPathDB/EbrcWebsiteCommon/assets/16354313/a5446441-c618-4c9d-b809-f7c9d25d74fb)
