### ISSUE TITLE
SRT: Remainining download form issues

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/EbrcWebsiteCommon#193]
new redmine is https://redmine.apidb.org/issues/52746  (previous redmine got deleted by mistake)

(same as in PR https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/185, that has been closed)

The following are remaining known issues around downloading:

1. Mockup updated after UX meeting Jan 18 2023 https://docs.google.com/presentation/d/1m43IHO6BnkXHpusYR2cnJgWdgazm8jCy1euqBiNyKRA/edit#slide=id.p
2. Add a checkbox as in the tabular reporter to select one transcript per gene to all report forms where this is now supported. See https://github.com/VEuPathDB/ApiCommonWebsite/issues/117
3. Propagate the selection in the step result view filter, to the download form

See https://redmine.apidb.org/issues/47705 for any additional TODOs

spreadsheet:
https://docs.google.com/spreadsheets/d/1khvWWw2Vlazzj9MjsQRtIc4Bq9-FWyDUG-8cIKyqvxM/edit#gid=0

1. row 2: slow low complexity SQL  https://redmine.apidb.org/issues/50408
2. rows 3 and 6 are about handling limits and letting teh user know..  there are 2 PRs from wojtek: https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/188, https://github.com/VEuPathDB/ApiCommonWebsite/pull/126
3. row 4, empty result: https://github.com/VEuPathDB/ApiCommonWebsite/issues/130
4. row 5: i think it is the same as row 2 , slow , and requests a spinning wheel..

**Comment by aurreco-uga** [comment]
we released  so hopefully all done
